package com.java.musiconline.entities;
// Generated Jun 25, 2018 7:49:38 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Admin generated by hbm2java
 */
@Entity
@Table(name = "admin", catalog = "musiconline", uniqueConstraints = @UniqueConstraint(columnNames = "gmail"))
public class Admin implements java.io.Serializable {

	private Integer idAdmin;
	private String nameAdmin;
	private String gmail;
	private String password;

	public Admin() {
	}

	public Admin(String nameAdmin, String gmail, String password) {
		this.nameAdmin = nameAdmin;
		this.gmail = gmail;
		this.password = password;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idAdmin", unique = true, nullable = false)
	public Integer getIdAdmin() {
		return this.idAdmin;
	}

	public void setIdAdmin(Integer idAdmin) {
		this.idAdmin = idAdmin;
	}

	@Column(name = "nameAdmin", nullable = false, length = 200)
	public String getNameAdmin() {
		return this.nameAdmin;
	}

	public void setNameAdmin(String nameAdmin) {
		this.nameAdmin = nameAdmin;
	}

	@Column(name = "gmail", unique = true, nullable = false, length = 200)
	public String getGmail() {
		return this.gmail;
	}

	public void setGmail(String gmail) {
		this.gmail = gmail;
	}

	@Column(name = "password", nullable = false, length = 200)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
