package com.java.musiconline.entities;
// Generated Jun 25, 2018 7:49:38 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Banks generated by hbm2java
 */
@Entity
@Table(name = "banks", catalog = "musiconline")
public class Banks implements java.io.Serializable {

	private Integer idBank;
	private String nameBank;
	private Set<Bill> bill = new HashSet<Bill>(0);

	public Banks() {
	}

	public Banks(String nameBank) {
		this.nameBank = nameBank;
	}

	public Banks(String nameBank, Set<Bill> bill) {
		this.nameBank = nameBank;
		this.bill = bill;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idBank", unique = true, nullable = false)
	public Integer getIdBank() {
		return this.idBank;
	}

	public void setIdBank(Integer idBank) {
		this.idBank = idBank;
	}

	@Column(name = "nameBank", nullable = false, length = 200)
	public String getNameBank() {
		return this.nameBank;
	}

	public void setNameBank(String nameBank) {
		this.nameBank = nameBank;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "banks")
	public Set<Bill> getBill() {
		return this.bill;
	}

	public void setBill(Set<Bill> bill) {
		this.bill = bill;
	}

}
