package com.java.musiconline.entities;
// Generated Jun 25, 2018 7:49:38 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Bill generated by hbm2java
 */
@Entity
@Table(name = "bill", catalog = "musiconline")
public class Bill implements java.io.Serializable {

	private Integer idBill;
	private Banks banks;
	private String nameCus;
	private String phone;
	private String address;
	private int sates;
	private Date dates;
	private String summoney;
	private Set<Detailbill> detailbills = new HashSet<Detailbill>(0);

	public Bill() {
	}

	public Bill(Banks banks,String nameCus, String phone,String address, int sates, Date dates,String summoney) {
		this.banks = banks;
		this.nameCus = nameCus;
		this.phone = phone;
		this.address = address;
		this.sates = sates;
		this.dates = dates;
		this.summoney = summoney;
	}

	public Bill(Banks banks,String nameCus, String phone,String address, int sates, Date dates,String summoney, Set<Detailbill> detailbills) {
		this.banks = banks;
		this.nameCus = nameCus;
		this.phone = phone;
		this.address = address;
		this.sates = sates;
		this.dates = dates;
		this.summoney = summoney;
		this.detailbills = detailbills;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idBill", unique = true, nullable = false)
	public Integer getIdBill() {
		return this.idBill;
	}

	public void setIdBill(Integer idBill) {
		this.idBill = idBill;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idBank", nullable = false)
	public Banks getBanks() {
		return this.banks;
	}

	public void setBanks(Banks banks) {
		this.banks = banks;
	}
	
	@Column(name = "nameCus", nullable = false, length = 200)
	public String getNameCus() {
		return this.nameCus;
	}

	public void setNameCus(String nameCus) {
		this.nameCus = nameCus;
	}

	@Column(name = "phone", nullable = false, length = 200)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}
	@Column(name = "summoney", nullable = false, length = 200)
	public String getSummoney() {
		return this.summoney;
	}

	public void setSummoney(String summoney) {
		this.summoney = summoney;
	}
	
	@Column(name = "address", nullable = false, length = 200)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "sates", nullable = false)
	public int getSates() {
		return this.sates;
	}

	public void setSates(int sates) {
		this.sates = sates;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dates", nullable = false, length = 19)
	public Date getDates() {
		return this.dates;
	}

	public void setDates(Date dates) {
		this.dates = dates;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "bill")
	public Set<Detailbill> getDetailbills() {
		return this.detailbills;
	}

	public void setDetailbills(Set<Detailbill> detailbills) {
		this.detailbills = detailbills;
	}

	@Override
	public String toString() {
		return "Bill [idBill=" + idBill + ", banks=" + banks.getIdBank() + ", nameCus=" + nameCus + ", phone=" + phone
				+ ", address=" + address + ", sates=" + sates + ", dates=" + dates + ", summoney=" + summoney
				+ ", detailbills=" + detailbills + "]";
	}

}
