package com.java.musiconline.entities;
// Generated Jun 25, 2018 7:49:38 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Detailbill generated by hbm2java
 */
@Entity
@Table(name = "detailbill", catalog = "musiconline")
public class Detailbill implements java.io.Serializable {

	private Integer idDetailBill;
	
	private Bill bill;
	private Songs songs;
	private User user;
	private int countSong;
	private String price;

	public Detailbill() {
	}

	public Detailbill( Bill bill, Songs songs, User user, int countSong, String price) {
		
		this.bill = bill;
		this.songs = songs;
		this.user = user;
		this.countSong = countSong;
		this.price = price;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "IdDetailBill", unique = true, nullable = false)
	public Integer getIdDetailBill() {
		return this.idDetailBill;
	}

	public void setIdDetailBill(Integer idDetailBill) {
		this.idDetailBill = idDetailBill;
	}

	

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idBill", nullable = false)
	public Bill getBill() {
		return this.bill;
	}

	public void setBill(Bill bill) {
		this.bill = bill;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idSong", nullable = false)
	public Songs getSongs() {
		return this.songs;
	}

	public void setSongs(Songs songs) {
		this.songs = songs;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idUser", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "countSong", nullable = false)
	public int getCountSong() {
		return this.countSong;
	}

	public void setCountSong(int countSong) {
		this.countSong = countSong;
	}

	@Column(name = "price", nullable = false, length = 100)
	public String getPrice() {
		return this.price;
	}

	public void setPrice(String price) {
		this.price = price;
	}

}
