package com.java.musiconline.entities;
// Generated Jun 25, 2018 7:49:38 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Feels generated by hbm2java
 */
@Entity
@Table(name = "feels", catalog = "musiconline")
public class Feels implements java.io.Serializable {

	private Integer idFeels;
	private String nameFeels;
	private Set<Comment> comments = new HashSet<Comment>(0);
	private Set<ReplyComment> replyComments = new HashSet<ReplyComment>(0);

	public Feels() {
	}

	public Feels(String nameFeels) {
		this.nameFeels = nameFeels;
	}

	public Feels(String nameFeels, Set<Comment> comments, Set<ReplyComment> replyComments) {
		this.nameFeels = nameFeels;
		this.comments = comments;
		this.replyComments = replyComments;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idFeels", unique = true, nullable = false)
	public Integer getIdFeels() {
		return this.idFeels;
	}

	public void setIdFeels(Integer idFeels) {
		this.idFeels = idFeels;
	}

	@Column(name = "nameFeels", nullable = false, length = 50)
	public String getNameFeels() {
		return this.nameFeels;
	}

	public void setNameFeels(String nameFeels) {
		this.nameFeels = nameFeels;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "feels")
	public Set<Comment> getComments() {
		return this.comments;
	}

	public void setComments(Set<Comment> comments) {
		this.comments = comments;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "feels")
	public Set<ReplyComment> getReplyComments() {
		return this.replyComments;
	}

	public void setReplyComments(Set<ReplyComment> replyComments) {
		this.replyComments = replyComments;
	}

}
