package com.java.musiconline.entities;
// Generated Jun 25, 2018 7:49:38 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ReplyComment generated by hbm2java
 */
@Entity
@Table(name = "reply_comment", catalog = "musiconline")
public class ReplyComment implements java.io.Serializable {

	private Integer idReply;
	private Comment comment;
	private Feels feels;
	private Date repDates;
	private String repComtext;
	private String repName;

	public ReplyComment() {
	}

	public ReplyComment(Comment comment, Feels feels, Date repDates, String repComtext, String repName) {
		this.comment = comment;
		this.feels = feels;
		this.repDates = repDates;
		this.repComtext = repComtext;
		this.repName = repName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idReply", unique = true, nullable = false)
	public Integer getIdReply() {
		return this.idReply;
	}

	public void setIdReply(Integer idReply) {
		this.idReply = idReply;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idComment", nullable = false)
	public Comment getComment() {
		return this.comment;
	}

	public void setComment(Comment comment) {
		this.comment = comment;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idFeels", nullable = false)
	public Feels getFeels() {
		return this.feels;
	}

	public void setFeels(Feels feels) {
		this.feels = feels;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rep_dates", nullable = false, length = 19)
	public Date getRepDates() {
		return this.repDates;
	}

	public void setRepDates(Date repDates) {
		this.repDates = repDates;
	}

	@Column(name = "rep_comtext", nullable = false, length = 200)
	public String getRepComtext() {
		return this.repComtext;
	}

	public void setRepComtext(String repComtext) {
		this.repComtext = repComtext;
	}

	@Column(name = "rep_name", nullable = false, length = 100)
	public String getRepName() {
		return this.repName;
	}

	public void setRepName(String repName) {
		this.repName = repName;
	}

}
