package com.java.musiconline.entities;
// Generated Jun 25, 2018 7:49:38 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SongOfUser generated by hbm2java
 */
@Entity
@Table(name = "song_of_user", catalog = "musiconline")
public class SongOfUser implements java.io.Serializable {

	private Integer idSongUser;
	private Songs songs;
	private User user;

	public SongOfUser() {
	}

	public SongOfUser(Songs songs, User user) {
		this.songs = songs;
		this.user = user;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idSong_user", unique = true, nullable = false)
	public Integer getIdSongUser() {
		return this.idSongUser;
	}

	public void setIdSongUser(Integer idSongUser) {
		this.idSongUser = idSongUser;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idSong", nullable = false)
	public Songs getSongs() {
		return this.songs;
	}

	public void setSongs(Songs songs) {
		this.songs = songs;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idUser", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
