package com.java.musiconline.entities;
// Generated Jun 25, 2018 7:49:38 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Types generated by hbm2java
 */
@Entity
@Table(name = "types", catalog = "musiconline")
public class Types implements java.io.Serializable {

	private Integer idType;
	private String nameType;
	private Set<Songs> songses = new HashSet<Songs>(0);

	public Types() {
	}

	public Types(String nameType) {
		this.nameType = nameType;
	}

	public Types(String nameType, Set<Songs> songses) {
		this.nameType = nameType;
		this.songses = songses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idType", unique = true, nullable = false)
	public Integer getIdType() {
		return this.idType;
	}

	public void setIdType(Integer idType) {
		this.idType = idType;
	}

	@Column(name = "nameType", nullable = false, length = 200)
	public String getNameType() {
		return this.nameType;
	}

	public void setNameType(String nameType) {
		this.nameType = nameType;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "types")
	public Set<Songs> getSongses() {
		return this.songses;
	}

	public void setSongses(Set<Songs> songses) {
		this.songses = songses;
	}

}
